services:
  mariadb:
    image: mariadb:11.4
    container_name: tds_rodrigo_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: tds_rodrigo
    ports:
      - "3307:3306"
    volumes:
      - tds_rodrigo_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  tds_rodrigo_db_data:
